/*

 DUNGEON.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 17

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __dungeon_h_INCLUDE
#define __dungeon_h_INCLUDE

/* Bank of tiles. */
#define TileLabelBank 0

/* Super Gameboy palette 0 */
#define TileLabelSGBPal0c0 6076
#define TileLabelSGBPal0c1 8935
#define TileLabelSGBPal0c2 6596
#define TileLabelSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TileLabelSGBPal1c0 6076
#define TileLabelSGBPal1c1 8935
#define TileLabelSGBPal1c2 6596
#define TileLabelSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TileLabelSGBPal2c0 6076
#define TileLabelSGBPal2c1 8935
#define TileLabelSGBPal2c2 6596
#define TileLabelSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TileLabelSGBPal3c0 6076
#define TileLabelSGBPal3c1 8935
#define TileLabelSGBPal3c2 6596
#define TileLabelSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TileLabelCGBPal0c0 26226
#define TileLabelCGBPal0c1 23022
#define TileLabelCGBPal0c2 18761
#define TileLabelCGBPal0c3 14567

/* Gameboy Color palette 1 */
#define TileLabelCGBPal1c0 6378
#define TileLabelCGBPal1c1 23022
#define TileLabelCGBPal1c2 3204
#define TileLabelCGBPal1c3 14567

/* Gameboy Color palette 2 */
#define TileLabelCGBPal2c0 6076
#define TileLabelCGBPal2c1 8935
#define TileLabelCGBPal2c2 6596
#define TileLabelCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define TileLabelCGBPal3c0 6076
#define TileLabelCGBPal3c1 8935
#define TileLabelCGBPal3c2 6596
#define TileLabelCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define TileLabelCGBPal4c0 6076
#define TileLabelCGBPal4c1 8935
#define TileLabelCGBPal4c2 6596
#define TileLabelCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TileLabelCGBPal5c0 6076
#define TileLabelCGBPal5c1 8935
#define TileLabelCGBPal5c2 6596
#define TileLabelCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TileLabelCGBPal6c0 6076
#define TileLabelCGBPal6c1 8935
#define TileLabelCGBPal6c2 6596
#define TileLabelCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TileLabelCGBPal7c0 6076
#define TileLabelCGBPal7c1 8935
#define TileLabelCGBPal7c2 6596
#define TileLabelCGBPal7c3 5344

/* CGB palette entries. */
#define TileLabelCGB0 0
#define TileLabelCGB1 0
#define TileLabelCGB2 0
#define TileLabelCGB3 0
#define TileLabelCGB4 0
#define TileLabelCGB5 0
#define TileLabelCGB6 0
#define TileLabelCGB7 0
#define TileLabelCGB8 0
#define TileLabelCGB9 0
#define TileLabelCGB10 0
#define TileLabelCGB11 0
#define TileLabelCGB12 0
#define TileLabelCGB13 0
#define TileLabelCGB14 0
#define TileLabelCGB15 0
#define TileLabelCGB16 1
#define TileLabelCGB17 0
/* Start of tile array. */
extern const unsigned char TileLabel[];

#endif

/* End of DUNGEON.H */
