/*

 DUNGEON1.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 10
   Tile set      : C:\Users\lukeg\Desktop\dungeon.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define dungeon1Width 10
#define dungeon1Height 10
#define dungeon1Bank 0

unsigned char dungeon1[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x10,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x00
};

/* End of DUNGEON1.C */
