#include <gbdk/platform.h>
#include <gbdk/incbin.h>

#pragma bank 255
BANKREF(titlescreen)

#include <gbc_hicolor.h>

// Generated by png2hicolorgb

// Note: filepath is relative to the working directory of the tool that is calling it (often a makefile's working directory), NOT to the file it's being included into.

INCBIN(titlescreen_tiles,   "titlescreen.til")
INCBIN(titlescreen_map,     "titlescreen.map")
INCBIN(titlescreen_attr,    "titlescreen.atr")
INCBIN(titlescreen_palette, "titlescreen.pal")

INCBIN_EXTERN(titlescreen_tiles)
INCBIN_EXTERN(titlescreen_map)
INCBIN_EXTERN(titlescreen_attr)
INCBIN_EXTERN(titlescreen_palette)

const hicolor_data titlescreen_data = {
    .tile_count      = 167u,
    .height_in_tiles = 18u,
    .p_tiles         = titlescreen_tiles,
    .p_map           = titlescreen_map,
    .p_attribute_map = titlescreen_attr,
    .p_palette       = titlescreen_palette
};

