#include <gbdk/platform.h>

BANKREF_EXTERN(titlescreen)

#ifndef __titlescreen_h_
#define __titlescreen_h_

#include <gbc_hicolor.h>

// Generated by png2hicolorgb

extern const hicolor_data titlescreen_data;

#endif

