#define __TARGET_gb

#include <stdint.h>
#include <stdbool.h>
#include <gbdk/emu_debug.h>
#include <gb/gb.h>
#include <gbc_hicolor.h>
#include <titlescreen.h>
#include <gb/hardware.h>

// -----------------------------------------------------------------------------
// TITLE SCREEN VARIABLES
// -----------------------------------------------------------------------------

/**
 * @brief Flag that indicates whether the title screen is currently shown.
 *        If true, the game loop will typically skip normal gameplay.
 */
bool is_title_shown = false;

/**
 * @brief Pointer to the hi-color image data for the title screen.
 *        This data is generated by the png2hicolorgb tool.
 */
const hicolor_data* img_data;

/**
 * @brief The ROM bank where the title screen hi-color data resides.
 */
uint8_t img_bank;

// -----------------------------------------------------------------------------
// BANKED DATA POINTER FOR THE TITLE SCREEN IMAGE
// -----------------------------------------------------------------------------

/**
 * @struct banked_ptr_t
 * A small struct to hold both the bank number and a pointer to data.
 * This helps with referencing data that is located in another bank.
 */
typedef struct {
    uint8_t bank; // The bank number where data is stored
    const void* data; // Pointer to the actual data in that bank
} banked_ptr_t;

/**
 * @brief An instance describing the location of the hi-color title screen image.
 *        - The "BANK(titlescreen)" macro determines which bank the data is in.
 *        - "&HICOLOR_VAR(titlescreen)" references the actual hi-color data variable.
 */
const banked_ptr_t image = {
    BANK(titlescreen), // The bank used by the 'titlescreen' resource
    &HICOLOR_VAR(titlescreen) // The hi-color struct for the title screen
};

// -----------------------------------------------------------------------------
// TITLE SCREEN FUNCTIONS
// -----------------------------------------------------------------------------

/**
 * @brief Displays the title screen by loading the hi-color image data
 *        and enabling the hi-color rendering.
 *
 * This sets 'is_title_shown' so that the main game loop can detect that
 * the title screen is active.
 */
void show_titlescreen() {
    is_title_shown = true;

    // Retrieve the bank and hi-color data from our 'image' struct
    img_bank = image.bank;
    img_data = (const hicolor_data*)image.data;

    uint8_t saved_bank = _current_bank;
    if (img_bank) {
        SWITCH_ROM(img_bank); // Switch to the bank where the title screen data is
    }

    // Switch back if needed (though typically hicolor_start itself will do further bank usage)
    SWITCH_ROM(saved_bank);

    // Start hi-color mode with the loaded data
    hicolor_start(img_data, img_bank);
}

/**
 * @brief Cancels (closes) the title screen by stopping hi-color mode
 *        and marking the title as not shown.
 *
 * This will restore normal screen behavior so the game can continue.
 */
void cancel_titlescreen() {
    // Disable hi-color updates and revert to normal color usage
    hicolor_stop();

    // Signal that the title screen is no longer displayed
    is_title_shown = false;
}
